image:
    - Visual Studio 2015
    - Visual Studio 2017

configuration:
    - Release
    - Debug

      # Boost is already installed on AppVeyor.
environment:
    BOOST_ROOT: C:\Libraries\boost_1_64_0

init:
- echo %APPVEYOR_BUILD_WORKER_IMAGE%
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017%arch%" )
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" ( set generator="Visual Studio 14 2015%arch%" )
- echo %generator%

before_build:
- cmake -G %generator% -Dtrase_BUILD_OPENGL:BOOL=FALSE .

build:
  project: $(APPVEYOR_BUILD_FOLDER)\$(APPVEYOR_PROJECT_NAME).sln

test_script:
- '%APPVEYOR_BUILD_FOLDER%\%CONFIGURATION%\trase_test.exe -s'

