name: coverage

on:
  push:
    branches:
      - master
      - ci
  pull_request:
    branches:
      - '**'

jobs:

  build-and-test:
    name: Ubuntu unit ${{matrix.CC}}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: make build directory
        run: mkdir build_dir

      - name: cmake configure
        run: cmake .. -DCMAKE_BUILD_TYPE=Debug -Dtrase_BUILD_OPENGL:BOOL=FALSE -Dtrase_ENABLE_COVERAGE:BOOL=TRUE
        working-directory: build_dir

      - name: cmake build
        run: cmake --build . --parallel 2
        working-directory: build_dir

      - name: cmake test
        run: ctest -j2 --output-on-failure
        working-directory: build_dir

      - name: upload coverage results
        run: |
          lcov --directory . --capture --output-file coverage.info
          lcov --remove coverage.info '/usr/*' '*/tests/*' --output-file coverage.info
          lcov --list coverage.info
          bash <(curl https://codecov.io/bash) -f coverage.info -t 3e6f4afd-ffb4-4b78-8dff-9b62b545cffd
        working-directory: build_dir