name: validate and deploy files

on:
  push:
    branches:
      - master
      - ci
  pull_request:
    branches-ignore:
      - '**'

jobs:

  build-and-test:
    name: validate and deploy files
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: make build directory
        run: mkdir build_dir

      - name: cmake configure
        run: cmake .. -DCMAKE_BUILD_TYPE=Debug -Dtrase_BUILD_OPENGL:BOOL=FALSE
        working-directory: build_dir

      - name: cmake build
        run: cmake --build . --parallel 2
        working-directory: build_dir

      - name: cmake test
        run: ctest -j2 --output-on-failure
        working-directory: build_dir

      - name: validate svg
        run: |
          pip3 install --upgrade pip setuptools wheel
          pip3 install html5validator
          html5validator --root . --match "*.svg" --also-check-svg
        working-directory: build_dir

      - name: deploy files
        run: |
          git clone https://github.com/trase-cpp/generated_files.git
          rm generated_files/examples/*.svg
          rm generated_files/tests/*.svg
          cp examples/*.svg generated_files/examples/
          cp tests/*.svg generated_files/tests/
          cd generated_files
          git add examples/*.svg tests/*.svg
          git -c user.name='github-action' -c user.email='github-action' commit -a -m "updated generated files"
          git push -q https://martinjrobins:$GITHUB_API_KEY@github.com/trase-cpp/generated_files master &>/dev/null
        working-directory: build_dir
        env:
          GITHUB_API_KEY: ${{ secrets.GITHUB_API_KEY }}